/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ndubouil <ndubouil@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/01/11 10:24:46 by ndubouil          #+#    #+#             */
/*   Updated: 2018/06/24 20:06:53 by ndubouil         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../includes/libftprintf.h"
#include <limits.h>
#include <stdio.h>

int	main(void)
{
	int ret, ret2 = 0;

	ft_putendl("\n=========================================================> sans flags");
	ret = ft_printf("mine: %dABC\n", 42);
	ret2 = printf("real: %dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %dABC%dEFG\n", 42, 3);
	ret2 = printf("real: %dABC%dEFG\n", 42, 3);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %dABC\n", 2147483648);
	ret2 = printf("real: %dABC\n", 2147483648);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %dABC\n", -2147483648);
	ret2 = printf("real: %dABC\n", -2147483648);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %dABC\n", -42);
	ret2 = printf("real: %dABC\n", -42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: {YELLOW}{%d}ABC", -42);
	printf("\n");
	ret2 = printf("real: {YELLOW}{%d}ABC", -42);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: {CYAN}{%d}{EOC}ABC", -42);
	printf("\n");
	ret2 = printf("real: {CYAN}{%d}{EOC}ABC", -42);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %D", LONG_MIN);
	printf("\n");
	ret2 = printf("real: %D", LONG_MIN);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> mod longueur: hh");
	ret = ft_printf("mine: %hhdABC\n", 42);
	ret2 = printf("real: %hhdABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %hhdABC\n", 454);
	ret2 = printf("real: %hhdABC\n", 454);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %hhdABC\n", -300);
	ret2 = printf("real: %hhdABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %hhdABC\n", '42');
	ret2 = printf("real: %hhdABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("AAmine: %hhdABC\n", 100000000);
	ret2 = printf("AAreal: %hhdABC\n", 100000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %hhdABC\n", -258);
	ret2 = printf("real: %hhdABC\n", -258);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %hhdABC\n", 'X');
	ret2 = printf("real: %hhdABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> mod longueur: h");
	ret = ft_printf("mine: %hdABC\n", 42);
	ret2 = printf("real: %hdABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %hdABC\n", 300);
	ret2 = printf("real: %hdABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %hdABC\n", -300);
	ret2 = printf("real: %hdABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %hdABC\n", '42');
	ret2 = printf("real: %hdABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %hdABC\n", 3000000000);
	ret = ft_printf("mine: %hdABC\n", 'X');
	ret2 = printf("real: %hdABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %%%", 'X');
	ret2 = printf("real: %%%", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %%%%", 'X');
	ret2 = printf("real: %%%%", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> mod longueur: l");
	ret = ft_printf("mine: %ldABC\n", 42);
	ret2 = printf("real: %ldABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %ldABC\n", 300);
	ret2 = printf("real: %ldABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %ldABC\n", 1);
	ret2 = printf("real: %ldABC\n", 1);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %ldABC\n", '42');
	ret2 = printf("real: %ldABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %ldABC\n", 3000000000);
	ret2 = printf("real: %ldABC\n", 3000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %ldABC\n", -258);
	ret2 = printf("real: %ldABC\n", -258);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %ldABC\n", 'X');
	ret2 = printf("real: %ldABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> mod longueur: ll");
	ret = ft_printf("mine: %lldABC\n", 42);
	ret2 = printf("real: %lldABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lldABC\n", 300);
	ret2 = printf("real: %lldABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lldABC\n", -300);
	ret2 = printf("real: %lldABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lldABC\n", '42');
	ret2 = printf("real: %lldABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lldABC\n", 3000000000);
	ret2 = printf("real: %lldABC\n", 3000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lldABC\n", -258);
	ret2 = printf("real: %lldABC\n", -258);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lldABC\n", 'X');
	ret2 = printf("real: %lldABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ft_putendl("check valeurs max: ");
	ret = ft_printf("mine: %ldABC\n", LONG_MAX);
	ret2 = printf("real: %ldABC\n", LONG_MAX);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lldABC\n", -9223372036854775806); //gerer tout seul
	ret2 = printf("real: %lldABC\n", -9223372036854775806);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lldABC\n", -9223372036854775808); //gerer tout seul
	ret2 = printf("real: %lldABC\n", -9223372036854775808);
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> mod longueur: L");
	ret = ft_printf("mine: %LdABC\n", 42);
	ret2 = printf("real: %LdABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %LdABC\n", 300);
	ret2 = printf("real: %LdABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %LdABC\n", -300);
	ret2 = printf("real: %LdABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %LdABC\n", '42');
	ret2 = printf("real: %LdABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %LdABC\n", 3000000000);
	ret2 = printf("real: %LdABC\n", 3000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %LdABC\n", -258);
	ret2 = printf("real: %LdABC\n", -258);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %LdABC\n", 'X');
	ret2 = printf("real: %LdABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ft_putendl("check valeurs max: ");
	ret = ft_printf("mine: %LdABC\n", LONG_MAX);
	ret2 = printf("real: %LdABC\n", LONG_MAX);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %LdABC\n", -9223372036854775806); //gerer tout seul
	ret2 = printf("real: %LdABC\n", -9223372036854775806);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %LdABC\n", -9223372036854775808); //gerer tout seul
	ret2 = printf("real: %LdABC\n", -9223372036854775808);
	printf("RETURN | %d | %d\n\n", ret, ret2 );


	ft_putendl("\n=========================================================> mod longueur: j");
	ret = ft_printf("mine: %jdABC\n", 42);
	ret2 = printf("real: %jdABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %jdABC\n", 300);
	ret2 = printf("real: %jdABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %jdABC\n", -300);
	ret2 = printf("real: %jdABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %jdABC\n", '42');
	ret2 = printf("real: %jdABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %jdABC\n", 3000000000);
	ret2 = printf("real: %jdABC\n", 3000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %jdABC\n", -258);
	ret2 = printf("real: %jdABC\n", -258);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %jdABC\n", 'X');
	ret2 = printf("real: %jdABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> mod longueur: z");
	ret = ft_printf("mine: %zdABC\n", 42);
	ret2 = printf("real: %zdABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %zdABC\n", 300);
	ret2 = printf("real: %zdABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %zdABC\n", -300);
	ret2 = printf("real: %zdABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %zdABC\n", '42');
	ret2 = printf("real: %zdABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %zdABC\n", 3000000000);
	ret2 = printf("real: %zdABC\n", 3000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %zdABC\n", -258);
	ret2 = printf("real: %zdABC\n", -258);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %zdABC\n", 'X');
	ret2 = printf("real: %zdABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("%zd\n", -1);
	ret2 = printf("%zd\n", -1);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("%zd\n", 4294967296);
	ret2 = printf("%zd\n", 4294967296);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("%zd\n", 4294967298);
	ret2 = printf("%zd\n", 4294967298);
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> flag: aucun (avec field)");
	ret = ft_printf("mine: %10dABC\n", 42);
	ret2 = printf("real: %10dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %10dABC\n", 300);
	ret2 = printf("real: %10dABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %10dABC\n", -300);
	ret2 = printf("real: %10dABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %10dABC\n", '42');
	ret2 = printf("real: %10dABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %10dABC\n", 1000000000);
	ret2 = printf("real: %10dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %10dABC\n", -12);
	ret2 = printf("real: %10dABC\n", -12);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %10dABC\n", 'X');
	ret2 = printf("real: %10dABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );



	ft_putendl("\n=========================================================> flag: espace");
	ret = ft_printf("mine: % dABC\n", 42);
	ret2 = printf("real: % dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("% d\n", 42);
	ret2 = printf("% d\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % dABC\n", -42);
	ret2 = printf("real: % dABC\n", -42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % dABC\n", 300);
	ret2 = printf("real: % dABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % dABC\n", -300);
	ret2 = printf("real: % dABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % dABC\n", '42');
	ret2 = printf("real: % dABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % dABC\n", 1000000000);
	ret2 = printf("real: % dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % dABC\n", -12);
	ret2 = printf("real: % dABC\n", -12);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % dABC\n", 'X');
	ret2 = printf("real: % dABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> flag: + ");
	ret = ft_printf("mine: %+dABC\n", 42);
	ret2 = printf("real: %+dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+dABC\n", -42);
	ret2 = printf("real: %+dABC\n", -42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+dABC\n", 0);
	ret2 = printf("real: %+dABC\n", 0);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+dABC\n", 424242424242424242);
	ret2 = printf("real: %+dABC\n", 424242424242424242);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+dABC\n", 300);
	ret2 = printf("real: %+dABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+dABC\n", -300);
	ret2 = printf("real: %+dABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+dABC\n", '42');
	ret2 = printf("real: %+dABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+dABC\n", 1000000000);
	ret2 = printf("real: %+dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+dABC\n", -12);
	ret2 = printf("real: %+dABC\n", -12);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+dABC\n", 'X');
	ret2 = printf("real: %+dABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> flag: + (avec field)");
	ret = ft_printf("mine: %+10dABC\n", 42);
	ret2 = printf("real: %+10dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+10dABC\n", 300);
	ret2 = printf("real: %+10dABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+10dABC\n", -300);
	ret2 = printf("real: %+10dABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+10dABC\n", '42');
	ret2 = printf("real: %+10dABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+10dABC\n", 1000000000);
	ret2 = printf("real: %+10dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+10dABC\n", -12);
	ret2 = printf("real: %+10dABC\n", -12);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+10dABC\n", 'X');
	ret2 = printf("real: %+10dABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> flag: - (avec field)");
	ret = ft_printf("mine: %-4dABC\n", 42);
	ret2 = printf("real: %-4dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-4dABC\n", 300);
	ret2 = printf("real: %-4dABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-4dABC\n", -300);
	ret2 = printf("real: %-4dABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-4dABC\n", '42');
	ret2 = printf("real: %-4dABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-4dABC\n", 1000000000);
	ret2 = printf("real: %-4dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-4dABC\n", -12);
	ret2 = printf("real: %-4dABC\n", -12);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-4dABC\n", 'X');
	ret2 = printf("real: %-4dABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );


	ft_putendl("\n=========================================================> flag: 0 (avec field)");
	ret = ft_printf("mine: %010dABC\n", 42);
	ret2 = printf("real: %010dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %010dABC\n", 300);
	ret2 = printf("real: %010dABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %010dABC\n", -300);
	ret2 = printf("real: %010dABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %010dABC\n", '42');
	ret2 = printf("real: %010dABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %010dABC\n", 1000000000);
	ret2 = printf("real: %010dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %010dABC\n", -12);
	ret2 = printf("real: %010dABC\n", -12);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %010dABC\n", 'X');
	ret2 = printf("real: %010dABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	ft_putendl("\n=========================================================> Precision");
	ret = ft_printf("mine: %.10dABC\n", 42);
	ret2 = printf("real: %.10dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %.10dABC\n", 300);
	ret2 = printf("real: %.10dABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %.10dABC\n", -300);
	ret2 = printf("real: %.10dABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %.10dABC\n", '42');
	ret2 = printf("real: %.10dABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %.10dABC\n", 1000000000);
	ret2 = printf("real: %.10dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %.10dABC\n", -12);
	ret2 = printf("real: %.10dABC\n", -12);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %.10dABC\n", 'X');
	ret2 = printf("real: %.10dABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );


	ft_putendl("\n=========================================================> MELANGES");
	ret = ft_printf("mine: %0+5dABC\n", 42);
	ret2 = printf("real: %0+5dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+ dABC\n", 42);
	ret2 = printf("real: %+ dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+ dABC\n", -42);
	ret2 = printf("real: %+ dABC\n", -42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % +dABC\n", 42);
	ret2 = printf("real: % +dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % +dABC\n", -42);
	ret2 = printf("real: % +dABC\n", -42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-010dABC\n", 42);
	ret2 = printf("real: %-010dABC\n", 42);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-010dABC\n", 300);
	ret2 = printf("real: %-010dABC\n", 300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-010dABC\n", -300);
	ret2 = printf("real: %-010dABC\n", -300);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-010dABC\n", '42');
	ret2 = printf("real: %-010dABC\n", '42');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-010dABC\n", 1000000000);
	ret2 = printf("real: %-010dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-010dABC\n", -12);
	ret2 = printf("real: %-010dABC\n", -12);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-010dABC\n", 'X');
	ret2 = printf("real: %-010dABC\n", 'X');
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-#2.0dABC\n", 1000000000);
	ret2 = printf("real: %-#2.0dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %0#2.0dABC\n", 1000000000);
	ret2 = printf("real: %0#2.0dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret2 = printf("real: %-#2.0dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %0#2.0dABC\n", 1000000000);
	ret2 = printf("real: %0#2.0dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % 2.0dABC\n", 1000000000);
	ret2 = printf("real: % 2.0dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+15.12dABC\n", 1000000000); // + inactif avec 'x'
	ret2 = printf("real: %+15.12dABC\n", 1000000000);
	ret = ft_printf("mine: %03.2dABC\n", 0);
	ret2 = printf("real: %03.2dABC\n", 0);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %03.2dABC\n", 1);
	ret2 = printf("real: %03.2dABC\n", 1);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %#2.0dABC\n", 1000000000);
	ret2 = printf("real: %#2.0dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-2.0dABC\n", 1000000000);
	ret2 = printf("real: %-2.0dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %02.0dABC\n", 1000000000);
	ret2 = printf("real: %02.0dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % 2.0dABC\n", 1000000000);
	ret2 = printf("real: % 2.0dABC\n", 1000000000);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % 10.5dABC\n", 4242);
	ret2 = printf("real: % 10.5dABC\n", 4242);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %+10.5dABC\n", 4242);
	ret2 = printf("real: %+10.5dABC\n", 4242);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %-+10.5dABC\n", 4242);
	ret2 = printf("real: %-+10.5dABC\n", 4242);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %5.dABC%5.0dDEF\n", 0, 0);
	ret2 = printf("real: %5.dABC%5.0dDEF\n", 0, 0);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %zd\n", ULLONG_MAX);
	ret2 = printf("real: %zd\n", ULLONG_MAX);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %jd\n", ULLONG_MAX);
	ret2 = printf("real: %jd\n", ULLONG_MAX);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: % 03d\n", 0);
	ret2 = printf("real: % 03d\n", 0);
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("%D", 0L);
	ft_printf("\n");
	ret2 = printf("%D", 0L);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("%d", 0L);
	ft_printf("\n");
	ret2 = printf("%d", 0L);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lld", -9223372036854775808);
	ft_printf("\n");
	ret2 = printf("real: %lld", -9223372036854775808);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lld", -9223372036854775807);
	ft_printf("\n");
	ret2 = printf("real: %lld", -9223372036854775807);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %lld", -922);
	ft_printf("\n");
	ret2 = printf("real: %lld", -922);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %ld", -922);
	ft_printf("\n");
	ret2 = printf("real: %ld", -922);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %d", -922);
	ft_printf("\n");
	ret2 = printf("real: %d", -922);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );
	ret = ft_printf("mine: %Ld", 922);
	ft_printf("\n");
	ret2 = printf("real: %Ld", 922);
	printf("\n");
	printf("RETURN | %d | %d\n\n", ret, ret2 );

	return (0);
}
